### ISSUE TITLE
HiTAD - TypeError: 'NoneType object is not subscriptable'

### ISSUE THREAD

**Issue by StephenRicher** [XiaoTaoWang/TADLib#11]
Hi,

I am facing an error when running your HiTad tool and was wondering if you could help? I have created a cooler format HiC matrix using _cooler load_ from a 2D bedGraph-like file.

However when I try to run the hitad algorithm I received the following traceback.
![trackback_hitad](https://user-images.githubusercontent.com/45041598/59417932-080fc800-8dc0-11e9-91ad-bf4719815959.png)

I was wondering if you could help with this? I am using the 'raw' counts because my HiC matrix has already been balanced so these are in float type format. 

Thanks very much and thanks for creating this fantastic tool!

Stephen

**Comment by oriolfornes** [comment]
I am encountering the same error. For me, HiTAD was working correctly before I updated [`runHiC`](https://pypi.org/project/runHiC/) to the latest version.

**Comment by linhai1221** [comment]
I met the same problem, have you solve it stephen

**Comment by linhai1221** [comment]
I met the same problem, have you solved it, stephen

**Comment by XiaoTaoWang** [comment]
Hey guys,

Sorry for the delay. This bug was caused by outliers in HMM training for some datasets. Can you try the latest version (https://pypi.org/project/TADLib/) and let me know if it works?

Thanks!

**Comment by oriolfornes** [comment]
`pip install tadlib --upgrade` fixes it, thanks!

**Comment by linhai1221** [comment]
it works now, thanks
