### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by hisakawakuro** [XiaoTaoWang/TADLib#3]
Hi,

I got the following error:

tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:15: SubProcess-1: completed
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:15: Extract reproducible domains from replicates ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:15: Chrom 11 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:15: Chrom 10 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:16: Chrom 13 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:16: Chrom 12 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:16: Chrom 15 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:17: Chrom 14 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:17: Chrom 17 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:17: Chrom 16 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:18: Chrom 19 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:18: Chrom 18 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:19: Chrom 1 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:19: Chrom 3 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:20: Chrom 2 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:21: Chrom 5 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:21: Chrom 4 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:22: Chrom 7 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:23: Chrom 6 ...
tadlib.hitad.genomeLev    DEBUG   @ 01/02/18 10:05:24: Chrom 9 ...
Traceback (most recent call last):
  File "/public/home/soft/miniconda2/bin/hitad", line 123, in run
    G.callHierDomain(**kwargs)
  File "/public/home/soft/miniconda2/lib/python2.7/site-packages/tadlib/hitad/genomeLev.py", line 299, in callHierDomain
    mrep.callDomain()
  File "/public/home/soft/miniconda2/lib/python2.7/site-packages/tadlib/hitad/chromLev.py", line 1665, in callDomain
    tl = self._interp(self.reproducible(tg, qy))
  File "/public/home/soft/miniconda2/lib/python2.7/site-packages/tadlib/hitad/chromLev.py", line 1700, in reproducible
    self._extract(tbase, pool, tg)
  File "/public/home/soft/miniconda2/lib/python2.7/site-packages/tadlib/hitad/chromLev.py", line 1854, in _extract
    assert not bounds is None
AssertionError

What happend ?

**Comment by XiaoTaoWang** [comment]
This assertion error indicates some unexpected domain alignment cases. Could you please run hitad on your two replicates independently and email the two domain lists to wangxiaotao868@163.com? This will be helpful for me to debug the code.

**Comment by XiaoTaoWang** [comment]
Sorry, but hitad doesn't support 3 or more replicates. I'll consider it in next version. For now, you can run hitad on the pooled data, or split the pooled data into 2 pseudo replicates.
