### ISSUE TITLE
The  matrix file from HiC-Pro  could be used as hitad input?

### ISSUE THREAD

**Issue by liufuyan2016** [XiaoTaoWang/TADLib#4]
Dear professor,
 

Only intra-chromosomal contacts are allowed and they should be stored chromosome by chromosome in text files. These files should be named following the pattern chr*.txt and be placed under the same folder, where “*” indicates the chromosome labels (1,2,...,X,Y for human). Each file should contain 3 columns (separated by whitespace):

<bin1> <bin2> <IF>
bin1, bin2: bin index on the corresponding chromosome
IF : normalized/corrected interaction frequency

I want to known the matrix file from HIC-Pro　could be used here? Thanks you!

**Comment by XiaoTaoWang** [comment]
Any hic data processing software should be okay, as long as they can output these necessary information.

**Comment by oriolfornes** [comment]
Dear Xiao,

I have a (probably stupid) question regarding the use of `HiC-Pro` and `TADLib` for analyzing mouse `Hi-C` data. Being the input as simple as `<bin1> <bin2> <IF>` (`int` `int` `float`), how does `TADLib` recognize the coordinates in the mouse genome if no labels for the bins (_e.g._ `data_40000_abs.bed` from HiC-Pro) are provided?
