### ISSUE TITLE
Cooler format and Python3 support

### ISSUE THREAD

**Issue by Nanguage** [XiaoTaoWang/TADLib#6]
Hello,

I have read your paper, it's really a very good algorithm I think.
But it will be better if support a more standard file format like 'cooler' or '.hic'.
Because the .npz is not a standard file format, there are many way to create and read it, 
it's hard to integrate with other softwares.

At the same time, the Python ecosystem will not support the Python2 anymore at the future,
see [this](http://python3statement.org/).  As a user, I want to use it under the Python3 environment.
Have you consider transplant projects to Python3?

This is just a suggestion, it does not affect the normal use of the software.
If it bothers you, please ignore and close this issue.

Thank you.

**Comment by XiaoTaoWang** [comment]
Thanks a lot for your suggestions. I understand being consistent with common interface standards will contribute a lot to larger software ecosystems. And I do decide to make it compatible with python3. You will see these changes in next version.

**Comment by dangdachang** [comment]
Hello，
I‘m trying to apply your wonderful algorithm to some Hi-C datasets. I want to know the input file of hitad is 0-based or 1-based, which means the bin in the .txt or .npz file should start with 0 or 1. I can't recognize this from your  example data because the bins start with 401.

Thanks a lot!

**Comment by XiaoTaoWang** [comment]
Hello, HiTAD assumes that the bin index starts from 0. If you have any other questions, please let know.

**Comment by dangdachang** [comment]
Thanks a lot!
