### ISSUE TITLE
A question about running HiTAD 

### ISSUE THREAD

**Issue by dangdachang** [XiaoTaoWang/TADLib#7]
Hello,  I have tried to apply HiTAD to two different Hi-C data. On one dataset, the resolution is 40kb,  it worked and I got result like this  ：
![success](https://user-images.githubusercontent.com/29725415/45029550-9f9afa00-b07b-11e8-8bdf-58131ce1444b.PNG)

On the other dataset, the resolution is 50kb but it failed and return the error like this:

![fail](https://user-images.githubusercontent.com/29725415/45030026-20a6c100-b07d-11e8-9e93-b58f8e3e6eac.PNG)

I checked  the DIs calculated by the script and I found it is zero for every bin which means DIs = array([0,0,0,...,0,0,0]).
I don't know why this happened, I dealed with the two datasets the same way. And the only difference between them is the resolution, I want to know how can I avoid this error ? Will it works if I change some parameters when deal with the 50kb dataset? 

Any advice will be helpful, thanks!

**Comment by dangdachang** [comment]
I  realize this is because the threshold of noiselevel in function oriWindow is too small for my second dataset.  I adjust it to 0.5 and run the script again, it works.

**Comment by XiaoTaoWang** [comment]
Hello. Sorry for the delay of reply. But I notice that the resolution you set for the 2nd dataset was still 40000, which could cause some unexpected errors indeed, right?

Best wishes!

**Comment by dangdachang** [comment]
Hello, yes ,I notice the resolution was wrong in the picture above, I reset the resolution to 50000, but it still can't work. But when I adjust the noiselevel to 0.5, it worked, I think this parameter should be adjusted according to the data of Hi-C.

**Comment by XiaoTaoWang** [comment]
Thanks for the feedback! I'll try to fix this bug in the following version.
