### ISSUE TITLE
ValueError: Empty DI sequences for HMM training

### ISSUE THREAD

**Issue by chenxq815** [XiaoTaoWang/TADLib#8]
Hi, I used the hitad to call TADs with 40 kb resolution. It is doubt that some chromosomes works and some not.  The error as followed with the common "hitad -O chr02.txt -p 6 -d datasets-onerep_40kb -C ":
![default](https://user-images.githubusercontent.com/24214348/46246191-1da8b180-c42c-11e8-99fd-ffaa6a87ff4f.png)
Chromosomes named as followed:
![default](https://user-images.githubusercontent.com/24214348/46246126-6c098080-c42b-11e8-902d-f662ebfd3e8e.png)
 Thanks ！

**Comment by XiaoTaoWang** [comment]
Hey, it seems your contact matrix is too sparse at this resolution.

**Comment by XiaoTaoWang** [comment]
Hi, I have changed some internal parameters to make it work for noisy matrix in the latest version 0.4.0 (https://pypi.org/project/TADLib/), you can try it and feel free to let me know if it still outputs this error.
