### ISSUE TITLE
How to dela with the overlap between Conserved TAD boundarie and Sub-TAD to TAD boundaries from tadlib.hitad.aligner

### ISSUE THREAD

**Issue by liufuyan2016** [XiaoTaoWang/TADLib#9]
Recently , I use the tadlib.hitad.aligner for compare the TAD s from two samples and get the Conserved TAD boundarie and Sub-TAD to TAD boundaries . But I found there are overlap for one boudary. So ,Could you tell me does this boundary  belong to Conserved TAD boundarie or  Sub-TAD to TAD boundaries? Thanks you very much!

**Comment by shenlinyong** [comment]
TADlib is a super great software . Iwould like to ask a question about the use of `tadlib.hitad.aligner`. #19 
Thank you very much.
